var questions = [
  {q:"1. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"2. Inside which HTML element do we put the JavaScript?",
  answers:["script", "scripting", "javascript", "js"],
  correct:"script"},
  {q:"3. What is the correct?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"4. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"5. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"6. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"7. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"8. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"9. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"10. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"11. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"12. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"13. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"14. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"15. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"16. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"17. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"18. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"19. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
  {q:"20. Which of the following is not a primitive?",
  answers:["Arrays", "Integers", "Strings", "Functions"],
  correct:"Arrays"},
];
